name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Installing lint
        run: make lint-install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
